### ISSUE TITLE
File application missing on Apache image / container

### ISSUE THREAD

**Issue by g7morris** [Islandora-Collaboration-Group/ISLE#184]
#### Issue description

When ingesting samples (e.g. Audio, Video, PDFs and Basic Images), FITS reports an error with the `file` application.

[File application on Ubuntu.](http://manpages.ubuntu.com/manpages/cosmic/man1/file.1.html) 

When I `docker exec -it isle-apache-ld bash` on a running ISLE Apache container, the `file` application cannot be found at a typical location `/usr/bin/file`

In essence, this application isn't installed on the Apache container etc and should be installed with the apache image being rebuilt. Recommend an addition to the Dockerfile.

#### Steps to reproduce the issue

1.   `docker exec -it isle-apache-ld bash`
2.  `which file`

A. Ingest samples and review FITS logs (_not persisted_)

#### What's the expected result?

- That the `file` application is typically installed on an Ubuntu system however in this case it is understandable on a Docker container that it might not. 

#### What's the actual result?

```
2018-10-19 21:03:14 - ERROR - FileUtility:74 - File Utility cannot be used on this system
2018-10-19 21:03:14 - ERROR - ToolBelt:138 - Thread 1 error initializing edu.harvard.hul.ois.fits.tools.fileutility.FileUtility: java.lang.InstantiationException  Message: edu.harvard.hul.ois.fits.tools.fileutility.FileUtility
java.lang.InstantiationException: edu.harvard.hul.ois.fits.tools.fileutility.FileUtility
	at java.lang.Class.newInstance(Class.java:427)
	at edu.harvard.hul.ois.fits.tools.ToolBelt.createToolClassInstance(ToolBelt.java:166)
	at edu.harvard.hul.ois.fits.tools.ToolBelt.init(ToolBelt.java:120)
	at edu.harvard.hul.ois.fits.tools.ToolBelt.<init>(ToolBelt.java:56)
	at edu.harvard.hul.ois.fits.Fits.<init>(Fits.java:242)
	at edu.harvard.hul.ois.fits.Fits.<init>(Fits.java:122)
	at edu.harvard.hul.ois.fits.Fits.<init>(Fits.java:111)
	at edu.harvard.hul.ois.fits.Fits.main(Fits.java:293)
Caused by: java.lang.NoSuchMethodException: edu.harvard.hul.ois.fits.tools.fileutility.FileUtility.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.newInstance(Class.java:412)
```

**Comment by br2490** [comment]
👍 Thank you for this report.  Adding `file` to apache and will push build shortly.

**Comment by br2490** [comment]
Build in progress with new HASH 61a6066

**Comment by br2490** [comment]
Docker image uploaded to DH. Please `docker-compose pull` to pull the new image and test. 
If this is successful please report back and close ticket! We will post to the group if test passes.

**Comment by br2490** [comment]
@g7morris please verify the application is there an close this!

**Comment by g7morris** [comment]
@br2490 Thanks for the updates. 

Confirming now that when I `docker exec -it isle-apache-ld bash` and run 
`which file`, I now see `/usr/bin/file`. I've been able to repeat process on migrated sites as well. Closing ticket.
